### ISSUE TITLE
Games are not updating

### ISSUE THREAD

**Issue by gonrhcp** [currall/galaxy-integration-legendary#3]
I tested the update feature with the newest Fortnite update and it doesn't seem to launch.

I checked your code and I believe in plugin.py the line about updating the game is using a command that does not exist in legendary:
`os.system('start cmd.exe /c ""'+legendary_location+'\legendary.exe" update '+game_id+'"')`
I think the right command to update would be:
`legendary.exe install --update-only`
And if the update check is false, it should skip using:
`legendary.exe launch --skip-version-check`
Hope you can fix it soon, and keep up the good work !

**Comment by currall** [comment]
update is a supported command in legendary, but I think there was something wrong with how I checked the config file. See if it works in the latest release

**Comment by gonrhcp** [comment]
It does work now, I didn't know the update command was supported, since I didn't find it in the legendary command list on their GitHub page
Thanks !
